import Head from 'next/head'
import styles from '../styles/Main.module.scss'
import Image from 'next/image'

export default function Home() {
  

  return (
    <div className={styles.container}>
      <Head>
        <title>Shopka</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.navbar}>
          <div className={styles.logo}>
            <Image src={'/logo.svg'} width={174} height={41} />
          </div>

          <div className={styles.search__field}>
            <div className={styles.input__set}>
              <Image src={'/icons/search__icon.svg'} width={17.5} height={17.5}/>
              <input placeholder={'Поиск...'} type='search'/>

            </div>
          </div>

          <div className={styles.login__btn}>
            <button>Войти</button>
          </div>
        </div>
        <div className={styles.content}>
          <div className={styles.categories}>
            <button>Категории</button>
            <div>
              <p>Телефоны и смартфоны</p>
              <ul>
                <li><a>Телефоны</a></li>
                <li><a>Смартфоны</a></li>
              </ul>
              <p>Телефоны и смартфоны</p>
              <ul>
                <li><a>Телефоны</a></li>
                <li><a>Смартфоны</a></li>
              </ul>
              <p>Телефоны и смартфоны</p>
              <ul>
                <li><a>Телефоны</a></li>
                <li><a>Смартфоны</a></li>
              </ul>
            </div>
          </div>
          <div className={styles.goods}>

          </div>
        </div>
      </main>
    </div>
  )
}
