import Head from 'next/head'
import styles from '../styles/Main.module.scss'
import Image from 'next/image'
import Product from './components/product'
import Link from 'next/link'
import { useRef, useState } from 'react'

export default function Main() {
  const id = useRef(1)

  const [products, setProducts] = useState([])

  const createProduct = (name) => {
    const newProduct = {
      id: id.current
    }

    id.current += 1

    setProducts( (prev) => [...prev, newProduct])
  }


  return (
    <div className={styles.container}>
      <Head>
        <title>Shopka</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.navbar}>
          <div className={styles.logo}>
            <Image src={'/logo.svg'} width={174} height={41} />
          </div>
          <div className={styles.search__field}>
            <div className={styles.input__set}>
              <Image src={'/icons/search__icon.svg'} width={17.5} height={17.5}/>
              <input placeholder={'Поиск...'} type='search'/>
            </div>
          </div>
          <div className={styles.login__btn}>
            <button onClick={createProduct}>Войти</button>
          </div>
        </div>
        <div className={styles.content}>
          <div className={styles.categories}>
            <div className={styles.filtres}>
              <p>Телефоны и смартфоны</p>
              <ul>
                <li><a>Телефоны</a></li>
                <li><a>Смартфоны</a></li>
              </ul>
              <p>Ноутбуки и ПК</p>
              <ul>
                <li><a>Ноутбуки</a></li>
                <li><a>ПК</a></li>
              </ul>
              <p>Недвижимость</p>
              <ul>
                <li><a>Частный дом</a></li>
                <li><a>Квартира</a></li>
              </ul>
              <p>Одежда</p>
              <ul>
                <li><a>Зимняя</a></li>
                <li><a>Летняя</a></li>
              </ul>
              <p>Дом и сад</p>
              <ul>
                <li><a>Для дома</a></li>
                <li><a>Для сада</a></li>
              </ul>
            </div>
          </div>
          <div className={styles.wrapper}>
            <div className={styles.products}>
              {
                products.map( (product, idx) => {
                    return (
                        <>
                          <Link href={`/product/${product.id}`}>
                            <a>
                              <Product link={'/photo.jpeg'}></Product>
                            </a>
                          </Link>
                        </>
                    );
                })
              }
            </div>
          </div>
        </div>
      </main>
    </div>
  )
}
